package internal

import (
	"context"
	"fmt"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
)

type TrailListOutput struct {
	Body struct {
		Resources []string `json:"resources" doc:"Names of available trails"`
	}
}

type TrailInput struct {
	Name string `path:"name" doc:"Trail name"`
}

type TrailOutputBody struct {
	Body TrailOutput
}

type TrailOutput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	LengthMiles float64 `json:"length_miles"`
	Difficulty  string  `json:"difficulty" enum:"easy,moderate,hard"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

type TrailLineStyle string

const (
	TrailLineStyleSolid  TrailLineStyle = "solid"
	TrailLineStyleDashed TrailLineStyle = "dashed"
	TrailLineStyleDotted TrailLineStyle = "dotted"
)

// TrailSegment is a contiguous run of [longitude, latitude] coordinates with uniform visual style.
type TrailSegment struct {
	Coordinates [][2]float64   `json:"coordinates"`
	Color       string         `json:"color"`
	Style       TrailLineStyle `json:"style" enum:"solid,dashed,dotted"`
	Width       float64        `json:"width"`
}

type TrailGeometryOutput struct {
	Body struct {
		Segments []TrailSegment `json:"segments"`
	}
}

type POIIconType string

const (
	POIIconTrailhead POIIconType = "trailhead"
	POIIconParking   POIIconType = "parking"
	POIIconCampsite  POIIconType = "campsite"
	POIIconViewpoint POIIconType = "viewpoint"
	POIIconWater     POIIconType = "water"
	POIIconRestroom  POIIconType = "restroom"
	POIIconPicnic    POIIconType = "picnic"
	POIIconSummit    POIIconType = "summit"
	POIIconJunction  POIIconType = "junction"
	POIIconHazard    POIIconType = "hazard"
	POIIconHistoric  POIIconType = "historic"
	POIIconGeneral   POIIconType = "general"
)

type PointOfInterest struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Latitude    float64     `json:"latitude"`
	Longitude   float64     `json:"longitude"`
	IconType    POIIconType `json:"icon_type" enum:"trailhead,parking,campsite,viewpoint,water,restroom,picnic,summit,junction,hazard,historic,general"`
	ImageURL    *string     `json:"image_url,omitempty"`
}

type TrailPOIOutput struct {
	Body struct {
		POIs []PointOfInterest `json:"pois"`
	}
}

// stub data — replace with real storage later
var knownTrails = map[string]TrailOutput{
	"blue-ridge-loop": {
		Name:        "Blue Ridge Loop",
		Description: "A scenic loop through the Blue Ridge highlands.",
		LengthMiles: 4.2,
		Difficulty:  "moderate",
		Latitude:    36.7,
		Longitude:   -81.2,
	},
	"alpinetunnel": {
		Name:        "alpinetunnel",
		Description: "alpinetunnel",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"altalakes": {
		Name:        "Alta Lakes",
		Description: "altalakes",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"amphitheatre": {
		Name:        "amphitheatre",
		Description: "amphitheatre",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"animas": {
		Name:        "animas",
		Description: "animas",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"argentine": {
		Name:        "argentine",
		Description: "argentine",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"aspen": {
		Name:        "aspen",
		Description: "aspen",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"baldmtn": {
		Name:        "baldmtn",
		Description: "baldmtn",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"baldwin": {
		Name:        "baldwin",
		Description: "baldwin",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"ballard": {
		Name:        "ballard",
		Description: "ballard",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bangs": {
		Name:        "bangs",
		Description: "bangs",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"barbour": {
		Name:        "barbour",
		Description: "barbour",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"baxter": {
		Name:        "baxter",
		Description: "baxter",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bill": {
		Name:        "bill",
		Description: "bill",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"billings": {
		Name:        "billings",
		Description: "billings",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"billingsc": {
		Name:        "billingsc",
		Description: "billingsc",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"birdseye": {
		Name:        "birdseye",
		Description: "birdseye",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"blackbear": {
		Name:        "blackbear",
		Description: "blackbear",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"blacktail": {
		Name:        "blacktail",
		Description: "blacktail",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"blowout": {
		Name:        "blowout",
		Description: "blowout",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bolam": {
		Name:        "bolam",
		Description: "bolam",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"boreas": {
		Name:        "boreas",
		Description: "boreas",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bouldermtn": {
		Name:        "bouldermtn",
		Description: "bouldermtn",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"breakneck": {
		Name:        "breakneck",
		Description: "breakneck",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"brownmountain": {
		Name:        "brownmountain",
		Description: "brownmountain",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bull": {
		Name:        "bull",
		Description: "bull",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"bunce": {
		Name:        "bunce",
		Description: "bunce",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"calamity": {
		Name:        "calamity",
		Description: "calamity",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"californiagulch": {
		Name:        "californiagulch",
		Description: "californiagulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"californiapass": {
		Name:        "californiapass",
		Description: "californiapass",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    50.0,
		Longitude:   -30.0,
	},
	"caribou": {
		Name:        "Caribou City",
		Description: "Caribou City outside of Nederland, CO",
		LengthMiles: 4.2,
		Difficulty:  "moderate",
		Latitude:    39.9795,
		Longitude:   -105.5776,
	},
	"cascade": {
		Name:        "cascade",
		Description: "cascade",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cement": {
		Name:        "cement",
		Description: "cement",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"chalk": {
		Name:        "chalk",
		Description: "chalk",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"Chihuahua": {
		Name:        "Chihuahua",
		Description: "Chihuahua",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"chinamangulch": {
		Name:        "chinamangulch",
		Description: "chinamangulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"chinawall": {
		Name:        "chinawall",
		Description: "chinawall",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"chinns": {
		Name:        "chinns",
		Description: "chinns",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cinammon": {
		Name:        "cinammon",
		Description: "cinammon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cinnamongulch": {
		Name:        "cinnamongulch",
		Description: "cinnamongulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"clearlake": {
		Name:        "clearlake",
		Description: "clearlake",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"clohesy": {
		Name:        "clohesy",
		Description: "clohesy",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"coneyflats": {
		Name:        "coneyflats",
		Description: "coneyflats",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"coonhollow": {
		Name:        "coonhollow",
		Description: "coonhollow",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"corkscrew": {
		Name:        "corkscrew",
		Description: "corkscrew",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cottonwood": {
		Name:        "cottonwood",
		Description: "cottonwood",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cowcreek": {
		Name:        "cowcreek",
		Description: "cowcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"crookedcreek": {
		Name:        "crookedcreek",
		Description: "crookedcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cumberland": {
		Name:        "cumberland",
		Description: "cumberland",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cumberlandgulch": {
		Name:        "cumberlandgulch",
		Description: "cumberlandgulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"cunningham": {
		Name:        "cunningham",
		Description: "cunningham",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"dakan": {
		Name:        "dakan",
		Description: "dakan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"deercreek": {
		Name:        "deercreek",
		Description: "deercreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"democrat": {
		Name:        "democrat",
		Description: "democrat",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"devilscanyon": {
		Name:        "devilscanyon",
		Description: "devilscanyon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"dextercreek": {
		Name:        "dextercreek",
		Description: "dextercreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"dolores": {
		Name:        "dolores",
		Description: "dolores",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"eaglerock": {
		Name:        "eaglerock",
		Description: "eaglerock",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"eldorado": {
		Name:        "eldorado",
		Description: "eldorado",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"elwood": {
		Name:        "elwood",
		Description: "elwood",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"engineer": {
		Name:        "engineer",
		Description: "engineer",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"eureka": {
		Name:        "eureka",
		Description: "eureka",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"fourmile": {
		Name:        "fourmile",
		Description: "fourmile",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"garibaldi": {
		Name:        "garibaldi",
		Description: "garibaldi",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"geneva": {
		Name:        "geneva",
		Description: "geneva",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"georgia": {
		Name:        "georgia",
		Description: "georgia",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"goldhill": {
		Name:        "goldhill",
		Description: "goldhill",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"goosecreek": {
		Name:        "goosecreek",
		Description: "goosecreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"gordon": {
		Name:        "gordon",
		Description: "gordon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"governor": {
		Name:        "governor",
		Description: "governor",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"granitecreek": {
		Name:        "granitecreek",
		Description: "granitecreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"greenridge": {
		Name:        "greenridge",
		Description: "greenridge",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"greer": {
		Name:        "greer",
		Description: "greer",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"grizzly": {
		Name:        "grizzly",
		Description: "grizzly",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"guanella": {
		Name:        "guanella",
		Description: "guanella",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"gunsight": {
		Name:        "gunsight",
		Description: "gunsight",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hackett": {
		Name:        "hackett",
		Description: "hackett",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hagerman": {
		Name:        "hagerman",
		Description: "hagerman",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"halfmoon": {
		Name:        "halfmoon",
		Description: "halfmoon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"halls": {
		Name:        "halls",
		Description: "halls",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hancock": {
		Name:        "hancock",
		Description: "hancock",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hancocklake": {
		Name:        "hancocklake",
		Description: "hancocklake",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"handcart": {
		Name:        "handcart",
		Description: "handcart",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hayden": {
		Name:        "hayden",
		Description: "hayden",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"heart": {
		Name:        "heart",
		Description: "heart",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hermit": {
		Name:        "hermit",
		Description: "hermit",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hiddenvalley": {
		Name:        "hiddenvalley",
		Description: "hiddenvalley",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"holycross": {
		Name:        "holycross",
		Description: "holycross",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"homestake": {
		Name:        "homestake",
		Description: "homestake",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"hurricane": {
		Name:        "hurricane",
		Description: "hurricane",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"imogene": {
		Name:        "imogene",
		Description: "imogene",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"independence": {
		Name:        "independence",
		Description: "independence",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"independencep": {
		Name:        "independencep",
		Description: "independencep",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"ironchest": {
		Name:        "ironchest",
		Description: "ironchest",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"ironclads": {
		Name:        "ironclads",
		Description: "ironclads",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"italian": {
		Name:        "italian",
		Description: "italian",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"jenny": {
		Name:        "jenny",
		Description: "jenny",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"johnbrown": {
		Name:        "johnbrown",
		Description: "johnbrown",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"johnny": {
		Name:        "johnny",
		Description: "johnny",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"jones": {
		Name:        "jones",
		Description: "jones",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"kebler": {
		Name:        "kebler",
		Description: "kebler",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"kellyflats": {
		Name:        "kellyflats",
		Description: "kellyflats",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"kennebec": {
		Name:        "kennebec",
		Description: "kennebec",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"kingston": {
		Name:        "kingston",
		Description: "kingston",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lamartine": {
		Name:        "lamartine",
		Description: "lamartine",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lasalle": {
		Name:        "lasalle",
		Description: "lasalle",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lastdollar": {
		Name:        "lastdollar",
		Description: "lastdollar",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"leadking": {
		Name:        "leadking",
		Description: "leadking",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"limecreek": {
		Name:        "limecreek",
		Description: "limecreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lochlomond": {
		Name:        "lochlomond",
		Description: "lochlomond",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"longwater": {
		Name:        "longwater",
		Description: "longwater",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lospinoscebolla": {
		Name:        "lospinoscebolla",
		Description: "lospinoscebolla",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lostcanyon": {
		Name:        "lostcanyon",
		Description: "lostcanyon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"lostpark": {
		Name:        "lostpark",
		Description: "lostpark",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"maggie": {
		Name:        "maggie",
		Description: "maggie",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mammoth": {
		Name:        "mammoth",
		Description: "mammoth",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"marshall": {
		Name:        "marshall",
		Description: "marshall",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mcallister": {
		Name:        "mcallister",
		Description: "mcallister",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"medano": {
		Name:        "medano",
		Description: "medano",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mettberry": {
		Name:        "mettberry",
		Description: "mettberry",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"middlestvrain": {
		Name:        "middlestvrain",
		Description: "middlestvrain",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"middleswan": {
		Name:        "middleswan",
		Description: "middleswan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"millcreek": {
		Name:        "millcreek",
		Description: "millcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"millerrock": {
		Name:        "millerrock",
		Description: "millerrock",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mineral": {
		Name:        "mineral",
		Description: "mineral",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"minerscreek": {
		Name:        "minerscreek",
		Description: "minerscreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"minersgulch": {
		Name:        "minersgulch",
		Description: "minersgulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"minnie": {
		Name:        "minnie",
		Description: "minnie",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"moodyhill": {
		Name:        "moodyhill",
		Description: "moodyhill",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"moon": {
		Name:        "moon",
		Description: "moon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mosquito": {
		Name:        "mosquito",
		Description: "mosquito",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountantero": {
		Name:        "mountantero",
		Description: "mountantero",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountbaldy": {
		Name:        "mountbaldy",
		Description: "mountbaldy",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountblanca": {
		Name:        "mountblanca",
		Description: "mountblanca",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountbross": {
		Name:        "mountbross",
		Description: "mountbross",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountmcclellan": {
		Name:        "mountmcclellan",
		Description: "mountmcclellan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountprincetown": {
		Name:        "mountprincetown",
		Description: "mountprincetown",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"mountzion": {
		Name:        "mountzion",
		Description: "mountzion",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"napoleon": {
		Name:        "napoleon",
		Description: "napoleon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"niche": {
		Name:        "niche",
		Description: "niche",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"nolan": {
		Name:        "nolan",
		Description: "nolan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"noname": {
		Name:        "noname",
		Description: "noname",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"northfork": {
		Name:        "northfork",
		Description: "northfork",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"northforkswan": {
		Name:        "northforkswan",
		Description: "northforkswan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"ohio": {
		Name:        "ohio",
		Description: "ohio",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"oldflowers": {
		Name:        "oldflowers",
		Description: "oldflowers",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"oldfulford": {
		Name:        "oldfulford",
		Description: "oldfulford",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"ophir": {
		Name:        "ophir",
		Description: "ophir",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"otto": {
		Name:        "otto",
		Description: "otto",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"owlcreek": {
		Name:        "owlcreek",
		Description: "owlcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pacelake": {
		Name:        "pacelake",
		Description: "pacelake",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"peak10": {
		Name:        "peak10",
		Description: "peak10",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"peak9": {
		Name:        "peak9",
		Description: "peak9",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pearl": {
		Name:        "pearl",
		Description: "pearl",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pennsylvania": {
		Name:        "pennsylvania",
		Description: "pennsylvania",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"peru": {
		Name:        "peru",
		Description: "peru",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"picayune": {
		Name:        "picayune",
		Description: "picayune",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pickle": {
		Name:        "pickle",
		Description: "pickle",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pinyon": {
		Name:        "pinyon",
		Description: "pinyon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pole": {
		Name:        "pole",
		Description: "pole",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"pomeroy": {
		Name:        "pomeroy",
		Description: "pomeroy",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"porphyry": {
		Name:        "porphyry",
		Description: "porphyry",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"poughkeepsie": {
		Name:        "poughkeepsie",
		Description: "poughkeepsie",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"ptarmigan": {
		Name:        "ptarmigan",
		Description: "ptarmigan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"radicalhill": {
		Name:        "radicalhill",
		Description: "radicalhill",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"rainbowfalls": {
		Name:        "rainbowfalls",
		Description: "rainbowfalls",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"rainbowfallsloop": {
		Name:        "rainbowfallsloop",
		Description: "rainbowfallsloop",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"rampartrange": {
		Name:        "rampartrange",
		Description: "rampartrange",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"redandwhite": {
		Name:        "redandwhite",
		Description: "redandwhite",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"redcanyon": {
		Name:        "redcanyon",
		Description: "redcanyon",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"redcone": {
		Name:        "redcone",
		Description: "redcone",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"redelephant": {
		Name:        "redelephant",
		Description: "redelephant",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"richmond": {
		Name:        "richmond",
		Description: "richmond",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"richmondbasin": {
		Name:        "richmondbasin",
		Description: "richmondbasin",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"rimrocker": {
		Name:        "rimrocker",
		Description: "rimrocker",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"rollins": {
		Name:        "rollins",
		Description: "rollins",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"saintjohn": {
		Name:        "saintjohn",
		Description: "saintjohn",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"santafe": {
		Name:        "santafe",
		Description: "santafe",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"saranwrap": {
		Name:        "saranwrap",
		Description: "saranwrap",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"schofield": {
		Name:        "schofield",
		Description: "schofield",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"scotchcreek": {
		Name:        "scotchcreek",
		Description: "scotchcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"sheepcreek": {
		Name:        "sheepcreek",
		Description: "sheepcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"sheephorn": {
		Name:        "sheephorn",
		Description: "sheephorn",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"sheridan": {
		Name:        "sheridan",
		Description: "sheridan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"shrine": {
		Name:        "shrine",
		Description: "shrine",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"sidney": {
		Name:        "sidney",
		Description: "sidney",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"slate": {
		Name:        "slate",
		Description: "slate",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"slaughterhouse": {
		Name:        "slaughterhouse",
		Description: "slaughterhouse",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"slide": {
		Name:        "slide",
		Description: "slide",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"springcreek": {
		Name:        "springcreek",
		Description: "springcreek",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"springcreekrd": {
		Name:        "springcreekrd",
		Description: "springcreekrd",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"SSwan": {
		Name:        "SSwan",
		Description: "SSwan",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"stillwater": {
		Name:        "stillwater",
		Description: "stillwater",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"stonypass": {
		Name:        "stonypass",
		Description: "stonypass",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"summitville": {
		Name:        "summitville",
		Description: "summitville",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"switzerland": {
		Name:        "switzerland",
		Description: "switzerland",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"tabeguache": {
		Name:        "tabeguache",
		Description: "tabeguache",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"taylor": {
		Name:        "taylor",
		Description: "taylor",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"taylormount": {
		Name:        "taylormount",
		Description: "taylormount",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"tincup": {
		Name:        "tincup",
		Description: "tincup",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"tomichi": {
		Name:        "tomichi",
		Description: "tomichi",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"transfer": {
		Name:        "transfer",
		Description: "transfer",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"treasure": {
		Name:        "treasure",
		Description: "treasure",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"turner": {
		Name:        "turner",
		Description: "turner",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"twincone": {
		Name:        "twincone",
		Description: "twincone",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"uncompahgre": {
		Name:        "uncompahgre",
		Description: "uncompahgre",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"uncompahgredivide": {
		Name:        "uncompahgredivide",
		Description: "uncompahgredivide",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"uranium": {
		Name:        "uranium",
		Description: "uranium",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"usbasin": {
		Name:        "usbasin",
		Description: "usbasin",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"wager": {
		Name:        "wager",
		Description: "wager",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"warden": {
		Name:        "warden",
		Description: "warden",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"washington": {
		Name:        "washington",
		Description: "washington",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"wearyman": {
		Name:        "wearyman",
		Description: "wearyman",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"webster": {
		Name:        "webster",
		Description: "webster",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"weston": {
		Name:        "weston",
		Description: "weston",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"wheeler": {
		Name:        "wheeler",
		Description: "wheeler",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"wheelerg": {
		Name:        "wheelerg",
		Description: "wheelerg",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"williams": {
		Name:        "williams",
		Description: "williams",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"wurtsditch": {
		Name:        "wurtsditch",
		Description: "wurtsditch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"yankee": {
		Name:        "yankee",
		Description: "yankee",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"yankeehill": {
		Name:        "yankeehill",
		Description: "yankeehill",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
	"yansinggulch": {
		Name:        "yansinggulch",
		Description: "yansinggulch",
		LengthMiles: 1.0,
		Difficulty:  "hard",
		Latitude:    51.0,
		Longitude:   -31.0,
	},
}

var knownTrailGeometry = map[string][]TrailSegment{
	"caribou": {
		{
			Coordinates: [][2]float64{
				{-105.5820, 39.9760},
				{-105.5800, 39.9775},
				{-105.5776, 39.9795},
			},
			Color: "#4caf50",
			Style: TrailLineStyleSolid,
			Width: 4,
		},
		{
			Coordinates: [][2]float64{
				{-105.5776, 39.9795},
				{-105.5750, 39.9810},
				{-105.5730, 39.9830},
			},
			Color: "#ff9800",
			Style: TrailLineStyleDashed,
			Width: 4,
		},
		{
			Coordinates: [][2]float64{
				{-105.5730, 39.9830},
				{-105.5710, 39.9820},
				{-105.5700, 39.9800},
			},
			Color: "#e05c5c",
			Style: TrailLineStyleDotted,
			Width: 4,
		},
	},
}

var knownTrailPOIs = map[string][]PointOfInterest{
	"caribou": {
		{
			Name:        "Caribou Ranch Trailhead",
			Description: "Main trailhead with a small parking area. The trail begins here and follows an old mining road into the hills.",
			Latitude:    39.981061,
			Longitude:   -105.578660,
			IconType:    POIIconTrailhead,
		},
		{
			Name:        "Caribou Town Site",
			Description: "Site of the former Caribou silver mining town, active from the 1870s through the 1890s. Several building foundations are still visible.",
			Latitude:    39.987209,
			Longitude:   -105.577186,
			IconType:    POIIconHistoric,
		},
		{
			Name:        "Ridge Viewpoint",
			Description: "Open ridgeline with sweeping views of the Indian Peaks Wilderness to the west and the Front Range to the east.",
			Latitude:    39.993123,
			Longitude:   -105.571700,
			IconType:    POIIconViewpoint,
		},
		{
			Name:        "North Boulder Creek Crossing",
			Description: "Seasonal stream crossing. Water is generally reliable spring through mid-summer; may be dry by late August.",
			Latitude:    40.000402,
			Longitude:   -105.560042,
			IconType:    POIIconWater,
		},
		{
			Name:        "Mine Shaft Hazard",
			Description: "Remnant open mine shaft — stay on trail and keep pets on leash. Do not approach the shaft opening.",
			Latitude:    39.990446,
			Longitude:   -105.575621,
			IconType:    POIIconHazard,
		},
	},
}

func registerTrailRoutes(api huma.API) {
	huma.Register(api, huma.Operation{
		OperationID: "list-trails",
		Method:      http.MethodGet,
		Path:        "/trail",
		Summary:     "List trails",
		Tags:        []string{"Trails"},
	}, func(ctx context.Context, _ *struct{}) (*TrailListOutput, error) {
		out := &TrailListOutput{}
		for name := range knownTrails {
			out.Body.Resources = append(out.Body.Resources, name)
		}
		return out, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-trail",
		Method:      http.MethodGet,
		Path:        "/trail/{name}",
		Summary:     "Get trail metadata",
		Tags:        []string{"Trails"},
	}, func(ctx context.Context, input *TrailInput) (*TrailOutputBody, error) {
		trail, ok := knownTrails[input.Name]
		if !ok {
			return nil, huma.Error404NotFound(fmt.Sprintf("trail %q not found", input.Name))
		}
		return &TrailOutputBody{
			Body: trail,
		}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-trail-geometry",
		Method:      http.MethodGet,
		Path:        "/trail/{name}/geometry",
		Summary:     "Get trail line geometry",
		Tags:        []string{"Trails"},
	}, func(ctx context.Context, input *TrailInput) (*TrailGeometryOutput, error) {
		trail, ok := knownTrails[input.Name]
		if !ok {
			return nil, huma.Error404NotFound(fmt.Sprintf("trail %q not found", input.Name))
		}
		segments, ok := knownTrailGeometry[input.Name]
		if !ok {
			segments = []TrailSegment{{
				Coordinates: [][2]float64{
					{trail.Longitude - 0.005, trail.Latitude},
					{trail.Longitude + 0.005, trail.Latitude},
				},
				Color: "#4fc3f7",
				Style: TrailLineStyleSolid,
				Width: 3,
			}}
		}
		out := &TrailGeometryOutput{}
		out.Body.Segments = segments
		return out, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-trail-pois",
		Method:      http.MethodGet,
		Path:        "/trail/{name}/pois",
		Summary:     "Get points of interest for a trail",
		Tags:        []string{"Trails"},
	}, func(ctx context.Context, input *TrailInput) (*TrailPOIOutput, error) {
		if _, ok := knownTrails[input.Name]; !ok {
			return nil, huma.Error404NotFound(fmt.Sprintf("trail %q not found", input.Name))
		}
		out := &TrailPOIOutput{}
		out.Body.POIs = knownTrailPOIs[input.Name]
		if out.Body.POIs == nil {
			out.Body.POIs = []PointOfInterest{}
		}
		return out, nil
	})
}
